foreground #212121
background #fafafa
selection_foreground #000000
selection_background #d0d0d0

cursor #000000
cursor_text_color #fafafa

active_border_color #3264eb
active_tab_background #3264eb

color0 #fafafa
color1 #c900c4
color2 #4a2fd0
color3 #026fde
color4 #3264eb
color5 #8a4ad7
color6 #0c67de
color7 #212121
color8 #9e9e9e
color9 #f930fb
color10 #9f85e0
color11 #358fff
color12 #5482ff
color13 #b363ff
color14 #3986ff
color15 #000000
