# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#faf4ed"

# Main text color
theme[main_fg]="#575279"

# Title color for boxes
theme[title]="#575279"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#56949f"

# Background color of selected item in processes box
theme[selected_bg]="#dfdad9"

# Foreground color of selected item in processes box
theme[selected_fg]="#56949f"

# Color of inactive/disabled text
theme[inactive_fg]="#cecacd"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#6e6a86"

# Background color of the percentage meters
theme[meter_bg]="#dfdad9"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#6e6a86"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#907aa9"
theme[mem_box]="#286983"
theme[net_box]="#b4637a"
theme[proc_box]="#56949f"

# Box divider line and small boxes line color
theme[div_line]="#cecacd"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#286983"
theme[temp_mid]="#ea9d34"
theme[temp_end]="#b4637a"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#d7827e"
theme[cpu_mid]="#56949f"
theme[cpu_end]="#907aa9"

# Mem/Disk free meter
theme[free_start]="#907aa9"
theme[free_mid]="#56949f"
theme[free_end]="#d7827e"

# Mem/Disk cached meter
theme[cached_start]="#56949f"
theme[cached_mid]="#d7827e"
theme[cached_end]="#907aa9"

# Mem/Disk available meter
theme[available_start]="#ea9d34"
theme[available_mid]="#b4637a"
theme[available_end]="#b4637a"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#286983"
theme[used_mid]="#d7827e"
theme[used_end]="#56949f"

# Download graph colors
theme[download_start]="#ea9d34"
theme[download_mid]="#b4637a"
theme[download_end]="#b4637a"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#286983"
theme[upload_mid]="#d7827e"
theme[upload_end]="#56949f"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#d7827e"
theme[process_mid]="#56949f"
theme[process_end]="#907aa9"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#faf4ed"
theme[gradient_color_1]="#f2e9e1"
theme[gradient_color_2]="#dfdad9"
theme[gradient_color_3]="#cecacd"
theme[gradient_color_4]="#9893a5"
theme[gradient_color_5]="#575279"
theme[gradient_color_6]="#6e6a86"
theme[gradient_color_7]="#575279"
